/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgeingReport: typeof import('./src/components/reports/AgeingReport.vue')['default']
    AgencyCard: typeof import('./src/components/ui/AgencyCard.vue')['default']
    AgencyModal: typeof import('./src/components/forms/AgencyModal.vue')['default']
    ClientModal: typeof import('./src/components/forms/ClientModal.vue')['default']
    ClientsSkeleton: typeof import('./src/components/skeletons/ClientsSkeleton.vue')['default']
    CommercialSchedule: typeof import('./src/components/reports/CommercialSchedule.vue')['default']
    ContractDetailsModal: typeof import('./src/components/modals/ContractDetailsModal.vue')['default']
    ContractModal: typeof import('./src/components/forms/ContractModal.vue')['default']
    DashboardSkeleton: typeof import('./src/components/skeletons/DashboardSkeleton.vue')['default']
    FallbackPage: typeof import('./src/components/FallbackPage.vue')['default']
    InvoiceModal: typeof import('./src/components/forms/InvoiceModal.vue')['default']
    InvoiceViewModal: typeof import('./src/components/modals/InvoiceViewModal.vue')['default']
    KPIBox: typeof import('./src/components/shared/KPIBox.vue')['default']
    PageSkeleton: typeof import('./src/components/skeletons/PageSkeleton.vue')['default']
    PartyLedger: typeof import('./src/components/reports/PartyLedger.vue')['default']
    PWAInstallPrompt: typeof import('./src/components/PWAInstallPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransmissionCertificateModal: typeof import('./src/components/modals/TransmissionCertificateModal.vue')['default']
  }
}
