/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgeingReport: typeof import('./src/components/reports/AgeingReport.vue')['default']
    AgencyCard: typeof import('./src/components/ui/AgencyCard.vue')['default']
    AgencyModal: typeof import('./src/components/forms/AgencyModal.vue')['default']
    ClientModal: typeof import('./src/components/forms/ClientModal.vue')['default']
    ClientsSkeleton: typeof import('./src/components/skeletons/ClientsSkeleton.vue')['default']
    CommercialSchedule: typeof import('./src/components/reports/CommercialSchedule.vue')['default']
    ContractDetailsModal: typeof import('./src/components/modals/ContractDetailsModal.vue')['default']
    ContractModal: typeof import('./src/components/forms/ContractModal.vue')['default']
    ContractSummaryReceiptModal: typeof import('./src/components/reports/ContractSummaryReceiptModal.vue')['default']
    ContractWisePaymentTable: typeof import('./src/components/tables/ContractWisePaymentTable.vue')['default']
    DashboardSkeleton: typeof import('./src/components/skeletons/DashboardSkeleton.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FallbackPage: typeof import('./src/components/FallbackPage.vue')['default']
    InvoiceModal: typeof import('./src/components/forms/InvoiceModal.vue')['default']
    InvoiceViewModal: typeof import('./src/components/modals/InvoiceViewModal.vue')['default']
    KPIBox: typeof import('./src/components/shared/KPIBox.vue')['default']
    PageSkeleton: typeof import('./src/components/skeletons/PageSkeleton.vue')['default']
    PartyLedger: typeof import('./src/components/reports/PartyLedger.vue')['default']
    PaymentList: typeof import('./src/components/tables/PaymentList.vue')['default']
    PaymentModal: typeof import('./src/components/forms/PaymentModal.vue')['default']
    PaymentReceiptModal: typeof import('./src/components/reports/PaymentReceiptModal.vue')['default']
    PWAInstallPrompt: typeof import('./src/components/PWAInstallPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransmissionCertificateModal: typeof import('./src/components/modals/TransmissionCertificateModal.vue')['default']
  }
}
